### ISSUE TITLE
Allow the generation of enums without `const`

### ISSUE THREAD

**Issue by ipvalverde** [Fignum/TypeGap#11]
The enums generated by TypeGap are generated using a `const`, something like this:

```typescript
    const enum MyEnum {
        Option1 = "value1",
        Option2 = "value2",
        Option3 = "value3",
    }
```

It would be nice to have a way to opt for a enum generation without the **const**, so the enum type would actually exist, allowing its manipulation, like the generation of a *HTML select* element based on an enum definition.

**Comment by caesay** [comment]
this is now possible
